#!/bin/bash

#PBS -N gizmo_dice_lowres
#PBS -P jh2
#PBS -q normal
#PBS -l ncpus=48
#PBS -l mem=190GB
#PBS -m aeb
#PBS -M ben.wibking@anu.edu.au
#PBS -l wd
#PBS -l walltime=12:00:00
#PBS -l storage=scratch/jh2+gdata/jh2
#PBS -l jobfs=400GB

# --- ensure we start in the correct directory ----

cd /g/data/jh2/bw0729/gizmo-fork/runs


# --- set MPI options ---
MPI_OPTIONS=""


# --- initialize GIZMO ---

mpirun $MPI_OPTIONS ./GIZMO isodisk-lowres.params > gizmo_isolated_disk_lowres.log 2>&1






