#!/bin/bash

#PBS -N dice_generate_ic_medres
#PBS -P jh2
#PBS -q normal
#PBS -l ncpus=48
#PBS -l mem=192GB
#PBS -m aeb
#PBS -M ben.wibking@anu.edu.au
#PBS -l wd
#PBS -l walltime=4:00:00
#PBS -l storage=scratch/jh2+gdata/jh2
#PBS -l jobfs=400GB

/g/data/jh2/bw0729/dice_install/bin/dice dice_isodisk_medres.config > dice_ic_gen_medres.log 2>&1

module load python3/3.7.4
python3 make_IC_medres.py dice_isodisk_medres.hdf5 > makeIC_medres.log 2>&1

