#!/bin/bash

#PBS -N dice_generate_ic
#PBS -P jh2
#PBS -q normal
#PBS -l ncpus=48
#PBS -l mem=192GB
#PBS -m aeb
#PBS -M ben.wibking@anu.edu.au
#PBS -l wd
#PBS -l walltime=24:00:00
#PBS -l storage=scratch/jh2+gdata/jh2
#PBS -l jobfs=400GB

/g/data/jh2/bw0729/dice_install/bin/dice dice_isodisk.config > dice_ic_gen.log 2>&1

module load python3/3.7.4
python3 make_IC.py dice_isodisk_superres.hdf5 > makeIC.log 2>&1

